clear;
clc;
G = tf(20, [1, 5, 4]);
err = 0.05;
zero = -0.1;
Gmf = feedback(G, 1);
polos = pole(Gmf);
disp('Polo 1 de Gmf:');
disp(polos(1));
sReal = real(polos(1));
sImag = imag(polos(1));
wn = sqrt(sReal^2 + sImag^2);
zeta = -sReal / wn;
disp('Coeficiente de amortecimento:');
disp(zeta);
disp('Frequência natural:');
disp(wn);
kp_ = 1 / err - 1;
disp('Constante de erro estático de posição:');
disp(kp_);
kp = 20 / 4;
b = kp_ / kp;
disp('B');
disp(b);
t = -1 / zero;
poloAtraso = -1 / (b*t);
disp('Polo do compensador de atraso:');
disp(poloAtraso);
disp('Os polos dominantes de mantém os mesmos');
s = sReal + sImag*1i;
kc_ = 1 / abs((s + zero) * 20/((s + poloAtraso)*(s+1)*(s+4)));
disp('Kc:');
disp(kc_);